# argocd-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/omargallob/argocd-clusterapi.git
    targetRevision: HEAD
    path: clusterapi-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true