apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: DockerMachineTemplate
metadata:
  name: controlplane
  namespace: default
spec:
  template:
    spec:
      extraMounts:
      - containerPath: "/var/lib/docker.sock"
        hostPath: "/var/lib/docker.sock"