apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: KubeadmControlPlane
metadata:
  name: controlplane
  namespace: default
spec:
  replicas: 1
  version: v1.34.0
  machineTemplate:
    spec:
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: DockerMachineTemplate
        name: controlplane
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        certSANs:
        - localhost
        - 127.0.0.1
        - 0.0.0.0
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          - name: "eviction-hard"
            value: "nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%"
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          - name: "eviction-hard"
            value: "nodefs.available<0%,nodefs.inodesFree<0%,imagefs.available<0%"